//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyMetadataAttribute("PublishTouch", "2026-05-22-rescale-republish")]
[assembly: System.Reflection.AssemblyCompanyAttribute("PolyCopyTrader.Domain")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+3b63e1384625a3ebbff5a779b115f317a3d7ff72")]
[assembly: System.Reflection.AssemblyProductAttribute("PolyCopyTrader.Domain")]
[assembly: System.Reflection.AssemblyTitleAttribute("PolyCopyTrader.Domain")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

